#!/system/bin/sh
# Default conservative settings

WATCHDOG_ENABLED=0
WATCHDOG_INTERVAL=120
RESTART_BT_ON_MISSING=0
RESTART_BT_ON_BAD_STATE=0
WHITELIST_BLUETOOTH=1
WHITELIST_GMS=1
WHITELIST_EXTRA_PACKAGES=""
ENABLE_WIFI_SCAN_THROTTLE_OFF=1
ENABLE_LOCATION_BG_THROTTLE_OFF=1
ENABLE_BLE_SCAN_ALWAYS=1
ENABLE_DEVICE_IDLE_TUNING=0
DEVICE_IDLE_CONSTANTS="inactive_to=86400000,sensing_to=600000,locating_to=600000"
MAX_RESTARTS_PER_HOUR=2
LOG_ROTATE_SIZE_KB=256
FAILURE_THRESHOLD=3
RECOVERY_COOLDOWN=600
MODE_DEFAULT="safe"
